version: "2"
services:
  cia-docker-composer:
    labels:
      "dmp.type": "example"
  java8:
    image: "java:8"
    ports:
      - "8080:8080"
    environment:
    ulimits:
      memlock:
        hard: 2048
        soft: 1024
